/**
 * Hardcoded restaurant data for the Restaurant Command Center prototype.
 * Restaurant: Spice Garden · Product: Explorex
 * No backend / API — all values are static dummy data for today.
 */

export const restaurant = {
  name: 'Spice Garden',
  product: 'Restaurant Command Center',
  company: 'Explorex',
  timezone: 'America/Los_Angeles',
  currency: 'USD',
  date: '2026-08-03',
}

/** @typedef {'available' | 'occupied' | 'waiting_for_bill'} TableStatus */

/**
 * 20 floor tables with mixed statuses.
 * seatingCapacity: guest seats at the table
 * server: assigned server name when occupied / waiting_for_bill
 * guests: current party size when occupied / waiting_for_bill
 * seatedAt: ISO time when the current party was seated (null if available)
 */
export const tables = [
  { id: 'T01', label: 'Table 1', section: 'Main', seatingCapacity: 2, status: 'occupied', guests: 2, server: 'Priya N.', seatedAt: '2026-08-03T11:42:00' },
  { id: 'T02', label: 'Table 2', section: 'Main', seatingCapacity: 2, status: 'available', guests: 0, server: null, seatedAt: null },
  { id: 'T03', label: 'Table 3', section: 'Main', seatingCapacity: 4, status: 'occupied', guests: 4, server: 'Marcus L.', seatedAt: '2026-08-03T12:05:00' },
  { id: 'T04', label: 'Table 4', section: 'Main', seatingCapacity: 4, status: 'waiting_for_bill', guests: 3, server: 'Priya N.', seatedAt: '2026-08-03T11:15:00' },
  { id: 'T05', label: 'Table 5', section: 'Main', seatingCapacity: 4, status: 'available', guests: 0, server: null, seatedAt: null },
  { id: 'T06', label: 'Table 6', section: 'Main', seatingCapacity: 6, status: 'occupied', guests: 5, server: 'Elena R.', seatedAt: '2026-08-03T12:20:00' },
  { id: 'T07', label: 'Table 7', section: 'Patio', seatingCapacity: 2, status: 'occupied', guests: 2, server: 'Jamal K.', seatedAt: '2026-08-03T12:35:00' },
  { id: 'T08', label: 'Table 8', section: 'Patio', seatingCapacity: 2, status: 'available', guests: 0, server: null, seatedAt: null },
  { id: 'T09', label: 'Table 9', section: 'Patio', seatingCapacity: 4, status: 'waiting_for_bill', guests: 4, server: 'Jamal K.', seatedAt: '2026-08-03T11:00:00' },
  { id: 'T10', label: 'Table 10', section: 'Patio', seatingCapacity: 4, status: 'occupied', guests: 3, server: 'Elena R.', seatedAt: '2026-08-03T12:48:00' },
  { id: 'T11', label: 'Table 11', section: 'Booth', seatingCapacity: 4, status: 'occupied', guests: 4, server: 'Marcus L.', seatedAt: '2026-08-03T11:55:00' },
  { id: 'T12', label: 'Table 12', section: 'Booth', seatingCapacity: 4, status: 'available', guests: 0, server: null, seatedAt: null },
  { id: 'T13', label: 'Table 13', section: 'Booth', seatingCapacity: 6, status: 'waiting_for_bill', guests: 6, server: 'Priya N.', seatedAt: '2026-08-03T10:50:00' },
  { id: 'T14', label: 'Table 14', section: 'Bar', seatingCapacity: 2, status: 'occupied', guests: 1, server: 'Sofia M.', seatedAt: '2026-08-03T12:10:00' },
  { id: 'T15', label: 'Table 15', section: 'Bar', seatingCapacity: 2, status: 'available', guests: 0, server: null, seatedAt: null },
  { id: 'T16', label: 'Table 16', section: 'Bar', seatingCapacity: 2, status: 'occupied', guests: 2, server: 'Sofia M.', seatedAt: '2026-08-03T12:40:00' },
  { id: 'T17', label: 'Table 17', section: 'Private', seatingCapacity: 8, status: 'occupied', guests: 7, server: 'Elena R.', seatedAt: '2026-08-03T11:30:00' },
  { id: 'T18', label: 'Table 18', section: 'Private', seatingCapacity: 8, status: 'available', guests: 0, server: null, seatedAt: null },
  { id: 'T19', label: 'Table 19', section: 'Main', seatingCapacity: 4, status: 'waiting_for_bill', guests: 2, server: 'Marcus L.', seatedAt: '2026-08-03T11:20:00' },
  { id: 'T20', label: 'Table 20', section: 'Main', seatingCapacity: 4, status: 'available', guests: 0, server: null, seatedAt: null },
]

/** Menu items referenced by orders */
export const menuItems = [
  { id: 'M01', name: 'Butter Chicken', category: 'Entree', price: 18.5 },
  { id: 'M02', name: 'Lamb Rogan Josh', category: 'Entree', price: 22.0 },
  { id: 'M03', name: 'Palak Paneer', category: 'Entree', price: 16.0 },
  { id: 'M04', name: 'Chicken Tikka Masala', category: 'Entree', price: 19.0 },
  { id: 'M05', name: 'Vegetable Biryani', category: 'Rice', price: 15.5 },
  { id: 'M06', name: 'Chicken Biryani', category: 'Rice', price: 17.5 },
  { id: 'M07', name: 'Garlic Naan', category: 'Bread', price: 4.5 },
  { id: 'M08', name: 'Butter Naan', category: 'Bread', price: 4.0 },
  { id: 'M09', name: 'Samosa (2 pcs)', category: 'Appetizer', price: 7.5 },
  { id: 'M10', name: 'Paneer Tikka', category: 'Appetizer', price: 12.0 },
  { id: 'M11', name: 'Mango Lassi', category: 'Beverage', price: 5.5 },
  { id: 'M12', name: 'Masala Chai', category: 'Beverage', price: 3.5 },
  { id: 'M13', name: 'Gulab Jamun', category: 'Dessert', price: 6.5 },
  { id: 'M14', name: 'Kheer', category: 'Dessert', price: 6.0 },
  { id: 'M15', name: 'Dal Makhani', category: 'Entree', price: 14.5 },
]

/**
 * Orders for today (2026-08-03).
 * status: pending | preparing | ready | served | completed | cancelled
 * Items reference menuItems by id; lineTotal = price * quantity
 */
export const orders = [
  {
    id: 'ORD-1001',
    tableId: 'T13',
    server: 'Priya N.',
    status: 'completed',
    placedAt: '2026-08-03T10:55:00',
    completedAt: '2026-08-03T12:40:00',
    items: [
      { menuItemId: 'M09', name: 'Samosa (2 pcs)', quantity: 2, unitPrice: 7.5, lineTotal: 15.0 },
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 2, unitPrice: 18.5, lineTotal: 37.0 },
      { menuItemId: 'M02', name: 'Lamb Rogan Josh', quantity: 2, unitPrice: 22.0, lineTotal: 44.0 },
      { menuItemId: 'M05', name: 'Vegetable Biryani', quantity: 1, unitPrice: 15.5, lineTotal: 15.5 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 4, unitPrice: 4.5, lineTotal: 18.0 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 3, unitPrice: 5.5, lineTotal: 16.5 },
      { menuItemId: 'M13', name: 'Gulab Jamun', quantity: 2, unitPrice: 6.5, lineTotal: 13.0 },
    ],
    subtotal: 159.0,
    tax: 14.31,
    tip: 28.0,
    total: 201.31,
  },
  {
    id: 'ORD-1002',
    tableId: 'T09',
    server: 'Jamal K.',
    status: 'completed',
    placedAt: '2026-08-03T11:05:00',
    completedAt: '2026-08-03T12:55:00',
    items: [
      { menuItemId: 'M10', name: 'Paneer Tikka', quantity: 1, unitPrice: 12.0, lineTotal: 12.0 },
      { menuItemId: 'M04', name: 'Chicken Tikka Masala', quantity: 2, unitPrice: 19.0, lineTotal: 38.0 },
      { menuItemId: 'M03', name: 'Palak Paneer', quantity: 1, unitPrice: 16.0, lineTotal: 16.0 },
      { menuItemId: 'M06', name: 'Chicken Biryani', quantity: 1, unitPrice: 17.5, lineTotal: 17.5 },
      { menuItemId: 'M08', name: 'Butter Naan', quantity: 3, unitPrice: 4.0, lineTotal: 12.0 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 2, unitPrice: 5.5, lineTotal: 11.0 },
    ],
    subtotal: 106.5,
    tax: 9.59,
    tip: 18.0,
    total: 134.09,
  },
  {
    id: 'ORD-1003',
    tableId: 'T04',
    server: 'Priya N.',
    status: 'served',
    placedAt: '2026-08-03T11:20:00',
    completedAt: null,
    items: [
      { menuItemId: 'M09', name: 'Samosa (2 pcs)', quantity: 1, unitPrice: 7.5, lineTotal: 7.5 },
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 1, unitPrice: 18.5, lineTotal: 18.5 },
      { menuItemId: 'M15', name: 'Dal Makhani', quantity: 1, unitPrice: 14.5, lineTotal: 14.5 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 2, unitPrice: 4.5, lineTotal: 9.0 },
      { menuItemId: 'M12', name: 'Masala Chai', quantity: 2, unitPrice: 3.5, lineTotal: 7.0 },
    ],
    subtotal: 56.5,
    tax: 5.09,
    tip: 0,
    total: 61.59,
  },
  {
    id: 'ORD-1004',
    tableId: 'T19',
    server: 'Marcus L.',
    status: 'served',
    placedAt: '2026-08-03T11:25:00',
    completedAt: null,
    items: [
      { menuItemId: 'M04', name: 'Chicken Tikka Masala', quantity: 1, unitPrice: 19.0, lineTotal: 19.0 },
      { menuItemId: 'M05', name: 'Vegetable Biryani', quantity: 1, unitPrice: 15.5, lineTotal: 15.5 },
      { menuItemId: 'M08', name: 'Butter Naan', quantity: 1, unitPrice: 4.0, lineTotal: 4.0 },
    ],
    subtotal: 38.5,
    tax: 3.47,
    tip: 0,
    total: 41.97,
  },
  {
    id: 'ORD-1005',
    tableId: 'T17',
    server: 'Elena R.',
    status: 'served',
    placedAt: '2026-08-03T11:35:00',
    completedAt: null,
    items: [
      { menuItemId: 'M09', name: 'Samosa (2 pcs)', quantity: 3, unitPrice: 7.5, lineTotal: 22.5 },
      { menuItemId: 'M10', name: 'Paneer Tikka', quantity: 2, unitPrice: 12.0, lineTotal: 24.0 },
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 2, unitPrice: 18.5, lineTotal: 37.0 },
      { menuItemId: 'M02', name: 'Lamb Rogan Josh', quantity: 2, unitPrice: 22.0, lineTotal: 44.0 },
      { menuItemId: 'M03', name: 'Palak Paneer', quantity: 1, unitPrice: 16.0, lineTotal: 16.0 },
      { menuItemId: 'M06', name: 'Chicken Biryani', quantity: 2, unitPrice: 17.5, lineTotal: 35.0 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 5, unitPrice: 4.5, lineTotal: 22.5 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 4, unitPrice: 5.5, lineTotal: 22.0 },
      { menuItemId: 'M13', name: 'Gulab Jamun', quantity: 3, unitPrice: 6.5, lineTotal: 19.5 },
    ],
    subtotal: 242.5,
    tax: 21.83,
    tip: 0,
    total: 264.33,
  },
  {
    id: 'ORD-1006',
    tableId: 'T01',
    server: 'Priya N.',
    status: 'served',
    placedAt: '2026-08-03T11:48:00',
    completedAt: null,
    items: [
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 1, unitPrice: 18.5, lineTotal: 18.5 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 1, unitPrice: 4.5, lineTotal: 4.5 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 2, unitPrice: 5.5, lineTotal: 11.0 },
    ],
    subtotal: 34.0,
    tax: 3.06,
    tip: 0,
    total: 37.06,
  },
  {
    id: 'ORD-1007',
    tableId: 'T11',
    server: 'Marcus L.',
    status: 'preparing',
    placedAt: '2026-08-03T12:00:00',
    completedAt: null,
    items: [
      { menuItemId: 'M10', name: 'Paneer Tikka', quantity: 1, unitPrice: 12.0, lineTotal: 12.0 },
      { menuItemId: 'M04', name: 'Chicken Tikka Masala', quantity: 2, unitPrice: 19.0, lineTotal: 38.0 },
      { menuItemId: 'M15', name: 'Dal Makhani', quantity: 1, unitPrice: 14.5, lineTotal: 14.5 },
      { menuItemId: 'M08', name: 'Butter Naan', quantity: 3, unitPrice: 4.0, lineTotal: 12.0 },
      { menuItemId: 'M14', name: 'Kheer', quantity: 2, unitPrice: 6.0, lineTotal: 12.0 },
    ],
    subtotal: 88.5,
    tax: 7.97,
    tip: 0,
    total: 96.47,
  },
  {
    id: 'ORD-1008',
    tableId: 'T03',
    server: 'Marcus L.',
    status: 'preparing',
    placedAt: '2026-08-03T12:10:00',
    completedAt: null,
    items: [
      { menuItemId: 'M09', name: 'Samosa (2 pcs)', quantity: 1, unitPrice: 7.5, lineTotal: 7.5 },
      { menuItemId: 'M02', name: 'Lamb Rogan Josh', quantity: 1, unitPrice: 22.0, lineTotal: 22.0 },
      { menuItemId: 'M03', name: 'Palak Paneer', quantity: 1, unitPrice: 16.0, lineTotal: 16.0 },
      { menuItemId: 'M05', name: 'Vegetable Biryani', quantity: 1, unitPrice: 15.5, lineTotal: 15.5 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 2, unitPrice: 4.5, lineTotal: 9.0 },
    ],
    subtotal: 70.0,
    tax: 6.3,
    tip: 0,
    total: 76.3,
  },
  {
    id: 'ORD-1009',
    tableId: 'T14',
    server: 'Sofia M.',
    status: 'ready',
    placedAt: '2026-08-03T12:15:00',
    completedAt: null,
    items: [
      { menuItemId: 'M15', name: 'Dal Makhani', quantity: 1, unitPrice: 14.5, lineTotal: 14.5 },
      { menuItemId: 'M08', name: 'Butter Naan', quantity: 1, unitPrice: 4.0, lineTotal: 4.0 },
      { menuItemId: 'M12', name: 'Masala Chai', quantity: 1, unitPrice: 3.5, lineTotal: 3.5 },
    ],
    subtotal: 22.0,
    tax: 1.98,
    tip: 0,
    total: 23.98,
  },
  {
    id: 'ORD-1010',
    tableId: 'T06',
    server: 'Elena R.',
    status: 'preparing',
    placedAt: '2026-08-03T12:25:00',
    completedAt: null,
    items: [
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 2, unitPrice: 18.5, lineTotal: 37.0 },
      { menuItemId: 'M04', name: 'Chicken Tikka Masala', quantity: 1, unitPrice: 19.0, lineTotal: 19.0 },
      { menuItemId: 'M06', name: 'Chicken Biryani', quantity: 1, unitPrice: 17.5, lineTotal: 17.5 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 3, unitPrice: 4.5, lineTotal: 13.5 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 3, unitPrice: 5.5, lineTotal: 16.5 },
    ],
    subtotal: 103.5,
    tax: 9.32,
    tip: 0,
    total: 112.82,
  },
  {
    id: 'ORD-1011',
    tableId: 'T07',
    server: 'Jamal K.',
    status: 'pending',
    placedAt: '2026-08-03T12:38:00',
    completedAt: null,
    items: [
      { menuItemId: 'M10', name: 'Paneer Tikka', quantity: 1, unitPrice: 12.0, lineTotal: 12.0 },
      { menuItemId: 'M03', name: 'Palak Paneer', quantity: 1, unitPrice: 16.0, lineTotal: 16.0 },
      { menuItemId: 'M08', name: 'Butter Naan', quantity: 2, unitPrice: 4.0, lineTotal: 8.0 },
    ],
    subtotal: 36.0,
    tax: 3.24,
    tip: 0,
    total: 39.24,
  },
  {
    id: 'ORD-1012',
    tableId: 'T16',
    server: 'Sofia M.',
    status: 'pending',
    placedAt: '2026-08-03T12:42:00',
    completedAt: null,
    items: [
      { menuItemId: 'M09', name: 'Samosa (2 pcs)', quantity: 1, unitPrice: 7.5, lineTotal: 7.5 },
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 1, unitPrice: 18.5, lineTotal: 18.5 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 1, unitPrice: 5.5, lineTotal: 5.5 },
    ],
    subtotal: 31.5,
    tax: 2.84,
    tip: 0,
    total: 34.34,
  },
  {
    id: 'ORD-1013',
    tableId: 'T10',
    server: 'Elena R.',
    status: 'pending',
    placedAt: '2026-08-03T12:50:00',
    completedAt: null,
    items: [
      { menuItemId: 'M04', name: 'Chicken Tikka Masala', quantity: 1, unitPrice: 19.0, lineTotal: 19.0 },
      { menuItemId: 'M02', name: 'Lamb Rogan Josh', quantity: 1, unitPrice: 22.0, lineTotal: 22.0 },
      { menuItemId: 'M05', name: 'Vegetable Biryani', quantity: 1, unitPrice: 15.5, lineTotal: 15.5 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 2, unitPrice: 4.5, lineTotal: 9.0 },
    ],
    subtotal: 65.5,
    tax: 5.9,
    tip: 0,
    total: 71.4,
  },
  {
    id: 'ORD-1014',
    tableId: null,
    server: 'Priya N.',
    status: 'completed',
    placedAt: '2026-08-03T10:20:00',
    completedAt: '2026-08-03T11:10:00',
    items: [
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 2, unitPrice: 18.5, lineTotal: 37.0 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 2, unitPrice: 4.5, lineTotal: 9.0 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 2, unitPrice: 5.5, lineTotal: 11.0 },
      { menuItemId: 'M13', name: 'Gulab Jamun', quantity: 1, unitPrice: 6.5, lineTotal: 6.5 },
    ],
    subtotal: 63.5,
    tax: 5.72,
    tip: 12.0,
    total: 81.22,
  },
  {
    id: 'ORD-1015',
    tableId: null,
    server: 'Jamal K.',
    status: 'completed',
    placedAt: '2026-08-03T10:40:00',
    completedAt: '2026-08-03T11:35:00',
    items: [
      { menuItemId: 'M06', name: 'Chicken Biryani', quantity: 2, unitPrice: 17.5, lineTotal: 35.0 },
      { menuItemId: 'M08', name: 'Butter Naan', quantity: 2, unitPrice: 4.0, lineTotal: 8.0 },
      { menuItemId: 'M12', name: 'Masala Chai', quantity: 2, unitPrice: 3.5, lineTotal: 7.0 },
    ],
    subtotal: 50.0,
    tax: 4.5,
    tip: 9.0,
    total: 63.5,
  },
  {
    id: 'ORD-1016',
    tableId: null,
    server: 'Marcus L.',
    status: 'completed',
    placedAt: '2026-08-03T11:00:00',
    completedAt: '2026-08-03T12:05:00',
    items: [
      { menuItemId: 'M09', name: 'Samosa (2 pcs)', quantity: 2, unitPrice: 7.5, lineTotal: 15.0 },
      { menuItemId: 'M04', name: 'Chicken Tikka Masala', quantity: 2, unitPrice: 19.0, lineTotal: 38.0 },
      { menuItemId: 'M03', name: 'Palak Paneer', quantity: 1, unitPrice: 16.0, lineTotal: 16.0 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 3, unitPrice: 4.5, lineTotal: 13.5 },
      { menuItemId: 'M14', name: 'Kheer', quantity: 2, unitPrice: 6.0, lineTotal: 12.0 },
    ],
    subtotal: 94.5,
    tax: 8.51,
    tip: 16.0,
    total: 119.01,
  },
  {
    id: 'ORD-1017',
    tableId: null,
    server: 'Elena R.',
    status: 'completed',
    placedAt: '2026-08-03T11:40:00',
    completedAt: '2026-08-03T12:30:00',
    items: [
      { menuItemId: 'M02', name: 'Lamb Rogan Josh', quantity: 1, unitPrice: 22.0, lineTotal: 22.0 },
      { menuItemId: 'M15', name: 'Dal Makhani', quantity: 1, unitPrice: 14.5, lineTotal: 14.5 },
      { menuItemId: 'M05', name: 'Vegetable Biryani', quantity: 1, unitPrice: 15.5, lineTotal: 15.5 },
      { menuItemId: 'M08', name: 'Butter Naan', quantity: 2, unitPrice: 4.0, lineTotal: 8.0 },
      { menuItemId: 'M11', name: 'Mango Lassi', quantity: 2, unitPrice: 5.5, lineTotal: 11.0 },
    ],
    subtotal: 71.0,
    tax: 6.39,
    tip: 14.0,
    total: 91.39,
  },
  {
    id: 'ORD-1018',
    tableId: null,
    server: 'Sofia M.',
    status: 'cancelled',
    placedAt: '2026-08-03T12:00:00',
    completedAt: '2026-08-03T12:08:00',
    items: [
      { menuItemId: 'M01', name: 'Butter Chicken', quantity: 1, unitPrice: 18.5, lineTotal: 18.5 },
      { menuItemId: 'M07', name: 'Garlic Naan', quantity: 1, unitPrice: 4.5, lineTotal: 4.5 },
    ],
    subtotal: 23.0,
    tax: 0,
    tip: 0,
    total: 0,
  },
]

/**
 * Revenue snapshot for today plus recent daily totals for trend charts.
 * All amounts in USD.
 */
export const revenue = {
  today: {
    date: '2026-08-03',
    grossSales: 1489.02,
    netSales: 1329.5,
    taxCollected: 119.52,
    tips: 97.0,
    refunds: 0,
    covers: 67,
    averageCheck: 55.15,
    ordersCompleted: 6,
    ordersInProgress: 11,
    ordersCancelled: 1,
  },
  byHour: [
    { hour: 10, sales: 144.72, orders: 2 },
    { hour: 11, sales: 627.53, orders: 6 },
    { hour: 12, sales: 716.77, orders: 9 },
    { hour: 13, sales: 0, orders: 0 },
    { hour: 14, sales: 0, orders: 0 },
    { hour: 15, sales: 0, orders: 0 },
    { hour: 16, sales: 0, orders: 0 },
    { hour: 17, sales: 0, orders: 0 },
    { hour: 18, sales: 0, orders: 0 },
    { hour: 19, sales: 0, orders: 0 },
    { hour: 20, sales: 0, orders: 0 },
    { hour: 21, sales: 0, orders: 0 },
  ],
  last7Days: [
    { date: '2026-07-28', grossSales: 4120.4, covers: 148, orders: 72 },
    { date: '2026-07-29', grossSales: 3855.1, covers: 139, orders: 68 },
    { date: '2026-07-30', grossSales: 4510.75, covers: 162, orders: 81 },
    { date: '2026-07-31', grossSales: 5288.2, covers: 185, orders: 94 },
    { date: '2026-08-01', grossSales: 6012.9, covers: 210, orders: 102 },
    { date: '2026-08-02', grossSales: 5740.35, covers: 198, orders: 97 },
    { date: '2026-08-03', grossSales: 1489.02, covers: 67, orders: 17 },
  ],
  topSellers: [
    { menuItemId: 'M01', name: 'Butter Chicken', quantitySold: 14, revenue: 259.0 },
    { menuItemId: 'M07', name: 'Garlic Naan', quantitySold: 25, revenue: 112.5 },
    { menuItemId: 'M04', name: 'Chicken Tikka Masala', quantitySold: 11, revenue: 209.0 },
    { menuItemId: 'M11', name: 'Mango Lassi', quantitySold: 19, revenue: 104.5 },
    { menuItemId: 'M02', name: 'Lamb Rogan Josh', quantitySold: 7, revenue: 154.0 },
  ],
  paymentMix: [
    { method: 'Card', share: 0.72, amount: 1072.09 },
    { method: 'Cash', share: 0.18, amount: 268.02 },
    { method: 'Mobile Wallet', share: 0.1, amount: 148.91 },
  ],
}

/** Floor occupancy helpers derived from tables */
export const floorSummary = {
  totalTables: tables.length,
  available: tables.filter((t) => t.status === 'available').length,
  occupied: tables.filter((t) => t.status === 'occupied').length,
  waitingForBill: tables.filter((t) => t.status === 'waiting_for_bill').length,
  currentGuests: tables.reduce((sum, t) => sum + t.guests, 0),
}

const data = {
  restaurant,
  tables,
  menuItems,
  orders,
  revenue,
  floorSummary,
}

export default data
